version: '3.1'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

#  app:
#    build:
#        context: .
#        dockerfile: Dockerfile
#    ports:
#      - "1323:1323"
#    environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379